### ISSUE TITLE
Make software installation more transparent (eg via docker)

### ISSUE THREAD

**Issue by gaow** [liangyy/deep_variant_annotation#1]
Hi @liangyy i took a look of your `setup.sh` on RCC. It seems you've configured a very specific environment that I cannot make it work easily on other machines for people without RCC access. I'm wondering if you are interested in helping me putting together a proper `docker` configuration to make your pipeline a lot more portable? For example eg I've done for the mash paper:

https://github.com/stephenslab/gtexresults/blob/master/workflows/mash.dockerfile

that case people do not need to worry about installing other software than docker itself. 

I'm asking because one of our colleagues (you surely know her xD) is going to need to run this on her desktop. Would be good if we can sort this out one way or another. Thanks!

**Comment by liangyy** [comment]
OK, I am willing to help. I'm new to docker. I will start with making a configuration file like the one you referred.

**Comment by gaow** [comment]
Ah I guess it might be more efficient if you could point me some documents on how exactly you configured the environment: a mardown file, a shell script etc. Do not worry about the English narratives. The commands and URL are most important. Ideally it should be as comprehensive as possible so presumably if I follow the instructions i can configure it on my machine flawlessly but do not push yourself to hard to achieve it. Just a very rough round of how it should work to the best of your knowledge. Then I can take from there. If i run into rough edges i'll reach out. 

BTW i noticed your envionments has also WASP etc. We'd here focus on a pure deepsea environment so it is best to keep it minimal. For WASP I actually have configured a docker image in case you are interested:

https://github.com/gaow/misc/blob/master/docker/wasp.dockerfile

and it has been used for production. I guess the deepsea + snakemake workflow image for this repo is more like this one.

**Comment by liangyy** [comment]
The pipeline mostly relies on the conda environment `deepvarpred_test`. The following is the result of `conda list -n deepvarpred_test`. I guess what I used for this particular pipeline is just `snakemake`, `pandas`, `keras 2.0.0`, `h5py`. `gzip`, `numpy`, etc. Other things are not relevent. 

https://gist.github.com/liangyy/5cb444e7182a17f3fe79902e94c43fbf

I guess to prepare these python3 packages is sufficient to run the pipeline.

**Comment by gaow** [comment]
That'd be a great start! Only keras has a version requirment not other packages? I'll just put together a docker image for now that contains the few packages you listed in your reply above; then we'll see if it can run out of the box and add new packages if there is a complaint. 

Could you add me collaborator to this repo if you think it is good idea that I push the docker file along with instructions directly into this repo?

**Comment by liangyy** [comment]
I guess only keras version is critical. Also, it may require theano as backend as well. 

I'll add you. It would be nice to have a setup instruction. Thanks!

**Comment by gaow** [comment]
Okay I added a Dockerfile (pretty simple!) and some setup instruction.  See patch above. To make it portable I had to change your Snakefile for the script dir. Have not tested due to permissin issue with your HDF5 file but when I get the file I'll test it and fix. I think I'll close the ticket for now as it should be fairly straightforward.

**Comment by gaow** [comment]
Okay to document one more additional dependency: `bedtools`.
