### ISSUE TITLE
Error when window size smaller than sequence length

### ISSUE THREAD

**Issue by gaow** [liangyy/deep_variant_annotation#2]
I got an error like this:

```
rule seq2input:
    input: /home/gaow/Documents/GIT/github/atac-gwas/test_var_deepsea/check.passed.ALT.tab.gz
    output: /home/gaow/Documents/GIT/github/atac-gwas/test_var_deepsea/input.ALT.hdf5
    jobid: 9
    wildcards: output_dir=/home/gaow/Documents/GIT/github/atac-gwas, name=test_var_deepsea, type=ALT


Traceback (most recent call last):
  File "/opt/deepann/seq2input.py", line 48, in <module>
    digit_seq[i, encode[seq[i]]] = 1
IndexError: index 1000 is out of bounds for axis 0 with size 1000
```

And looking at this line of code:

https://github.com/liangyy/deep_variant_annotation/blob/08e898fcc8232bd200dc343cb4f88dbb3fb082a2/scripts/seq2input.py#L43

Just from reading the code it seems that if `args.window` is less than `len(seq)` there will be index overflow error. Is that the case? I'm not sure how to propose a fix because I'm not seeing how `args.window` is useful in this script. ...

**Comment by liangyy** [comment]
Did this error come from running `test_var.txt`?
My first guess is `seq` is longer than 1000, whereas `args.window` should be 1000
One possibility to make `seq` longer than 1000 is that some variants are not SNP but indel.

**Comment by gaow** [comment]
I figured it out for this particular failure ... I checked `check.passed.ALT.tab.gz`  and noticed the sequence failed to properly break lines for some reason, leading to a long `seq` of 1118 characters. Then I realized there was a downgrade in my docker's OS from Debian Sid to Debian Buster when I was trying to install CUBA related stuff. And I looked into bedtools version that ships with Sid and Buster -- turns out bedtools has to be at either 2.25.x or 2.27.x but not 2.26.x. 

After specifying bedtools version number (to 2.25.x) the problem disappears for `test_var.txt`. 

However, I still do not understand the logic in that line of code. What happens if `len(seq)` is larger than `args.windows`. There will still be an issue right?

**Comment by liangyy** [comment]
At `rule var2seq_var2region`, it is ensured that `seq` length is `args.window`. Since 499 + 1 + 500 = 1000. I understand what it is not transparent and it is better to explicitly set `args.window` to 1000 rather than to use the default. One reason is that the models currently available work for window size 1000 only.

**Comment by gaow** [comment]
Thanks for the clarification. If it is by design to match the default window size then we should be good. And of course use the version of bedtools that works for your code!
